version: '3.8'

name: 'my-cas'

services:
  cas:
    image: remi/cas
    build: ./cas-overlay-template
    network_mode: bridge
    volumes:
      - ./etc/cas:/etc/cas:ro
    ports:
      - 127.0.0.1:8443:8443/tcp
      - 127.0.0.1:8081:8080/tcp